### ISSUE TITLE
[FR] 기존 config 파일에 누락된 정보가 있는 경우 기존정보 진행 못하게

### ISSUE THREAD

**Issue by SJang1** [SJang1/korea-covid-19-remaining-vaccine-macro#1045]
기존 config.ini에 현재 버전에서 누락되거나 수정된 정보가 있는 경우, 기존 정보로 계속 진행할 수 없도록 하는 업데이트

**Comment by oixhwotl** [comment]
config.ini의 백신 목록을 잘 못읽어 에러가 나는 문제가 있습니다.

config.ini 파일 생성후 실행시 발생되는 에러:
[현재 설정]
Traceback (most recent call last):
  File "/Users/jhlee/workspace/vaccine_wait/korea-covid-19-remaining-vaccine-macro/vaccine-run-kakao.py", line 30, in <module>
    main_function()
  File "/Users/jhlee/workspace/vaccine_wait/korea-covid-19-remaining-vaccine-macro/vaccine-run-kakao.py", line 17, in main_function
    previous_used_type, previous_top_x, previous_top_y, previous_bottom_x, previous_bottom_y, only_left = load_config()
  File "/Users/jhlee/workspace/vaccine_wait/korea-covid-19-remaining-vaccine-macro/kakao/config.py", line 117, in load_config
    print(f"백신 종류: {previous_used_type} ({next(x['name'] for x in vaccine_candidates if x['code'] == previous_used_type)})")
StopIteration

config.ini 내용:
[config]
vac = ["VEN00013"]
... (이하 생략)

kakao/config.py내 117 라인을 다음과 같이 변경했더니 잘 읽혀집니다.

diff --git a/kakao/config.py b/kakao/config.py
index 5ae6adc..fb591a1 100644
--- a/kakao/config.py
+++ b/kakao/config.py
@@ -114,7 +114,8 @@ def load_config():
                 close()

             print("\n[현재 설정]")
-            print(f"백신 종류: {previous_used_type} ({next(x['name'] for x in vaccine_candidates if x['code'] == previous_used_type)})")
+            #print(f"백신 종류: {previous_used_type} ({next(x['name'] for x in vaccine_candidates if x['code'] == previous_used_type)})")
+            print(f"백신 종류: { [(x['name'], x['code']) for x in vaccine_candidates if x['code'] in previous_used_type]}")
             print("top_x:", previous_top_x)
             print("top_y:", previous_top_y)
             print("bottom_x:", previous_bottom_x)

결과 해당 출력 부분:

[현재 설정]
백신 종류: [('화이자', 'VEN00013')]

kakao/config.py 수정시 이것도 참고하세요.
감사합니다.

**Comment by Queue-ri** [comment]
@oixhwotl 제보 감사합니다.
