### ISSUE TITLE
[BUG]  맥에서 실행시 버그

### ISSUE THREAD

**Issue by bjKim2** [SJang1/korea-covid-19-remaining-vaccine-macro#1061]
Traceback (most recent call last):
  File "browser_cookie3/__init__.py", line 354, in _decrypt
  File "pyaes/blockfeeder.py", line 169, in feed
  File "pyaes/blockfeeder.py", line 77, in _block_final_decrypt
  File "pyaes/util.py", line 58, in strip_PKCS7_padding
ValueError: invalid padding byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vaccine-run-kakao.py", line 30, in <module>
  File "vaccine-run-kakao.py", line 13, in main_function
  File "kakao/cookie.py", line 102, in load_cookie_from_chrome
  File "browser_cookie3/__init__.py", line 596, in chrome
  File "browser_cookie3/__init__.py", line 293, in load
  File "browser_cookie3/__init__.py", line 356, in _decrypt
browser_cookie3.BrowserCookieError: Unable to get key for cookie decryption
[912] Failed to execute script 'vaccine-run-kakao' due to unhandled exception!
Saving session...completed.

라고뜨뜹니다. 1~2주 전에 됬었는데 이번에 최신버전 다운받아서 하려니 안되네요.
chrome safe storage 키체인 요구해서 삭제후 실행했습니다.

**Comment by SJang1** [comment]
> chrome safe storage 키체인 요구해서 삭제후 실행했습니다.

해당 권한 요구 시 승인을 해주어야 합니다.. README에 권한 요구 시 승인 부탁드린다고 써놓았다시피..
