### ISSUE TITLE
browser_cookie3.BrowserCookieError: Failed to find Chrome cookie

### ISSUE THREAD

**Issue by jezsung** [SJang1/korea-covid-19-remaining-vaccine-macro#561]
맥에서 실행 시 해당 에러가 뜹니다

```
Traceback (most recent call last):
  File "vaccine-run-kakao.py", line 20, in <module>
  File "browser_cookie3/__init__.py", line 596, in chrome
  File "browser_cookie3/__init__.py", line 383, in __init__
  File "browser_cookie3/__init__.py", line 192, in __init__
  File "browser_cookie3/__init__.py", line 249, in __add_key_and_cookie_file
browser_cookie3.BrowserCookieError: Failed to find Chrome cookie
[2662] Failed to execute script 'vaccine-run-kakao' due to unhandled exception!
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[프로세스 완료됨]
```

**Comment by auroresky94** [comment]
i tried this and it worked~!!

jar = http.cookiejar.CookieJar()
chromecookies = os.path.join(os.path.expandvars("%userprofile%"),"AppData\\Local\\Google\\Chrome\\User Data\\Profile 1\\Cookies") ## finding cookie path
jar = browser_cookie3.chrome(cookie_file=chromecookies,domain_name=".kakao.com")
