### ISSUE TITLE
맥북에서 실행 이슈

### ISSUE THREAD

**Issue by yjks0415** [SJang1/korea-covid-19-remaining-vaccine-macro#607]
터미널에서 아래와 같은 메시지가 뜨면서 실행되지 않습니다.
Last login: Fri Jul 30 11:39:59 on ttys000
/Users/yjks0415/Downloads/dist/vaccine-run-kakao ; exit;

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Kimui-MacBook-Air:~ yjks0415$ /Users/yjks0415/Downloads/dist/vaccine-run-kakao ; exit;
Traceback (most recent call last):
  File "vaccine-run-kakao.py", line 20, in <module>
  File "browser_cookie3/__init__.py", line 596, in chrome
  File "browser_cookie3/__init__.py", line 383, in __init__
  File "browser_cookie3/__init__.py", line 192, in __init__
  File "browser_cookie3/__init__.py", line 249, in __add_key_and_cookie_file
browser_cookie3.BrowserCookieError: Failed to find Chrome cookie
[13501] Failed to execute script 'vaccine-run-kakao' due to unhandled exception!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[프로세스 완료됨]

**Comment by SJang1** [comment]
`Failed to find Chrome cookie`
크롬브라우저가 제대로 설치되어 있는지부터 프로파일이 뭔지 등등 점검해보세요.
