### ISSUE TITLE
[WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하 지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

### ISSUE THREAD

**Issue by Sang921** [SJang1/korea-covid-19-remaining-vaccine-macro#84]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Home\Desktop\korea-covid-19-remaining-vaccine-macro-main\vaccine-run-kakao.py", line 303, in <module>
    find_vaccine()
  File "C:\Users\Home\Desktop\korea-covid-19-remaining-vaccine-macro-main\vaccine-run-kakao.py", line 240, in find_vaccine
    response = requests.post(APIURL, data=json.dumps(APIdata), headers=headers.headers_map, cookies=jar, verify=False)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vaccine-map.kakao.com', port=443): Max retries exceeded with url: /api/v2/vaccine/left_count_by_coords (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021621D0DFA0>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하 지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

C:\Users\Home\Desktop\korea-covid-19-remaining-vaccine-macro-main>

==================================================================

해당 오류가 발생합니다. 최신버전으로 다운받아서 사용중이고 2개 켜서 작동했습니다.
아마 너무빠르게 지속적으로 조회를해서그런게 아닐까싶긴한데...
아참 말씀하신 쿠키모두허용/로그인상태유지/보안인증하기 까지 모두 완료된 상태입니다.

**Comment by SJang1** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/actions/runs/1064742607 하단에 있는 `Artifacts`에서 다시 받아서 실행해보실 수 있으신가요?

**Comment by SJang1** [comment]
링크 수정 : https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/actions/runs/1064752895

**Comment by SJang1** [comment]
확인해서 문제없으면 Close, 여전하면 Comment 부탁드립니다! ^^

**Comment by Sang921** [comment]
감사합니다

**Comment by Sang921** [comment]
Traceback (most recent call last):
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001DD32D2E460>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vaccine-map.kakao.com', port=443): Max retries exceeded with url: /api/v2/vaccine/left_count_by_coords (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD32D2E460>: Failed to establish a new connection: [WinError 10060]  연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Home\Desktop\korea-covid-19-remaining-vaccine-macro-main\vaccine-run-kakao.py", line 304, in <module>
    find_vaccine()
  File "C:\Users\Home\Desktop\korea-covid-19-remaining-vaccine-macro-main\vaccine-run-kakao.py", line 241, in find_vaccine
    response = requests.post(APIURL, data=json.dumps(APIdata), headers=headers.headers_map, cookies=jar, verify=False)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vaccine-map.kakao.com', port=443): Max retries exceeded with url: /api/v2/vaccine/left_count_by_coords (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD32D2E460>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

=========================================
엇 잘돌아가는줄알았더니.. 다시 이러한 오류가 발생하네요 ㅠ

**Comment by SJang1** [comment]
사용중인 환경을 알 수 있을까요?

**Comment by Sang921** [comment]
Window10 8700k / RTX3070 / 16GB램 입니다. pygame 2.0.1 (SDL 2.0.14, Python 3.9.6)
지금 최신버전 소스코드버전으로 돌려봣을때 해당오류는 발생하지않고 10분-20분 사이에 그냥 하나씩 종료되서 꺼져버리네요.
지금 윈도우 바이너리로 다시한번 10-20분 테스트 해보고 답글달겠습니다..

**Comment by SJang1** [comment]
사용중인 컴퓨터의 네트워크 상황도 확인해봐주세요. 네트워크가 끊겼을때 나타날 수 있는 문제입니다.

**Comment by Sang921** [comment]
바이너리돌리는건 총3개 돌렸는데 7분만에 하나 프로세스종료되었고 인터넷문제인가싶어서 일단 핑테스트랑 같이 돌려보고있습니다.. 늦은시간에도 빠른답변감사합니다

**Comment by Sang921** [comment]
핑테스트에서는 문제가없는데 하나가또죽어버렸네요..

**Comment by Sang921** [comment]
패킷전송은 문제없는데 프로그램이 꺼지는거는 이유를모르겠네요ㅎㅎ 바이러리 3개 구동중이었습니다

**Comment by Sang921** [comment]
해결은안됬지만 꺼지는거 무시하고 꺼질때마다 다시켜서 성공했습니다.. 감사합니다

**Comment by SJang1** [comment]
> 해결은안됬지만 꺼지는거 무시하고 꺼질때마다 다시켜서 성공했습니다.. 감사합니다

와! 성공하셨다니 축하드립니다! 백신 잘 맞고 오세요!
