### ISSUE TITLE
[BUG] RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by luftaquila** [SJang1/korea-covid-19-remaining-vaccine-macro#951]
**Describe the bug**
발견한 백신과 내가 지정한 백신이 다를 때 계속해서 예약 시도 후 선착순 마감이 반복되는데(#942) , 이 때 빈번하게 RecursionError가 발생합니다. 발생 위치는  https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/blob/db0432261c235400e9423e703622ef4d3698a0c0/kakao/request.py#L120 입니다.
`found_vaccine()`이 계속 자기 자신을 호출하다 보니 Traceback이 길어져서 생기는 문제 같습니다.

**Screenshots**
```
Traceback (most recent call last):
  File "C:\Users\LUFT-AQUILA\Downloads\korea-covid-19-remaining-vaccine-macro-main\vaccine-run-kakao.py", line 22, in main_function
    find_vaccine(cookie, search_time, vaccine_type, top_x, top_y, bottom_x, bottom_y, only_left)
  File "C:\Users\LUFT-AQUILA\Downloads\korea-covid-19-remaining-vaccine-macro-main\kakao\request.py", line 120, in find_vaccine
    find_vaccine(cookie, search_time, vaccine_type, top_x, top_y, bottom_x, bottom_y, only_left)
  File "C:\Users\LUFT-AQUILA\Downloads\korea-covid-19-remaining-vaccine-macro-main\kakao\request.py", line 120, in find_vaccine
    find_vaccine(cookie, search_time, vaccine_type, top_x, top_y, bottom_x, bottom_y, only_left)
  File "C:\Users\LUFT-AQUILA\Downloads\korea-covid-19-remaining-vaccine-macro-main\kakao\request.py", line 120, in find_vaccine
    find_vaccine(cookie, search_time, vaccine_type, top_x, top_y, bottom_x, bottom_y, only_left)
  File "C:\Users\LUFT-AQUILA\Downloads\korea-covid-19-remaining-vaccine-macro-main\kakao\request.py", line 117, in find_vaccine
    if vaccine_found_code and try_reservation(organization_code, vaccine_found_code, cookie):
  File "C:\Users\LUFT-AQUILA\Downloads\korea-covid-19-remaining-vaccine-macro-main\kakao\request.py", line 128, in try_reservation
    response = requests.post(reservation_url, data=json.dumps(data), headers=headers_vaccine, cookies=jar, verify=False)
  File "C:\Users\LUFT-AQUILA\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\LUFT-AQUILA\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\LUFT-AQUILA\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\LUFT-AQUILA\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\LUFT-AQUILA\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\LUFT-AQUILA\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\LUFT-AQUILA\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\LUFT-AQUILA\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\Program Files\Python39\lib\http\client.py", line 331, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "C:\Program Files\Python39\lib\http\client.py", line 225, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "C:\Program Files\Python39\lib\email\parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "C:\Program Files\Python39\lib\email\parser.py", line 56, in parse
    feedparser.feed(data)
  File "C:\Program Files\Python39\lib\email\feedparser.py", line 176, in feed
    self._call_parse()
  File "C:\Program Files\Python39\lib\email\feedparser.py", line 180, in _call_parse
    self._parse()
  File "C:\Program Files\Python39\lib\email\feedparser.py", line 295, in _parsegen
    if self._cur.get_content_maintype() == 'message':
  File "C:\Program Files\Python39\lib\email\message.py", line 594, in get_content_maintype
    ctype = self.get_content_type()
  File "C:\Program Files\Python39\lib\email\message.py", line 578, in get_content_type
    value = self.get('content-type', missing)
  File "C:\Program Files\Python39\lib\email\message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "C:\Program Files\Python39\lib\email\_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
  File "C:\Program Files\Python39\lib\email\_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
  File "C:\Program Files\Python39\lib\email\utils.py", line 57, in _has_surrogates
    s.encode()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Environment (please complete the following information):**
 - OS: 윈도우 10
 - Program Version: main 브랜치 vaccine-run.kakao.py (Python 3.9.5)

**Comment by LeeJoonkyu** [comment]
macos 동일 버전에서도 같은 에러 발생중입니다.
