### ISSUE TITLE
KeyError: 'cookie_values'

### ISSUE THREAD

**Issue by skang29** [SJang1/korea-covid-19-remaining-vaccine-macro#967]
1.0.30 버전으로 업데이트 후 `vaccine-run-kakao-windows.exe` 실행 시 동일 환경에서 아래와 같은 에러가 발생합니다.

```
C:\Users\skang\Desktop\vaccine> .\vaccine-run-kakao-windows_10030.exe
Traceback (most recent call last):
  File "C:\Users\skang\AppData\Local\Temp\ON765F~1\vaccine-run-kakao.py", line 28, in <module>
  File "C:\Users\skang\AppData\Local\Temp\ON765F~1\vaccine-run-kakao.py", line 11, in main_function
  File "C:\Users\skang\AppData\Local\Temp\ON765F~1\kakao\cookie.py", line 48, in load_saved_cookie
  File "C:\Users\skang\AppData\Local\Temp\ON765F~1\configparser.py", line 963, in __getitem__
KeyError: 'cookie_values'
```

`cookie.ini`에는 아래와 같이 적혀 있습니다.
```
[chrome]
cookie_file=C:\Users\skang\AppData\Local\Google\Chrome\User Data\Profile 2\Cookies
```

확인 부탁드립니다!

**Comment by jinh0** [comment]
`cookie.ini` 속안에 `[chrome]`처럼 `[cookie_values]`가 없어서 오류가 나타납니다. 제가 이거 고치는 PR 당장 만들겠습니다.

지금 당장 문제를 해결하고 싶으면, `cookie.ini` 안에 [cookie_values]와 _kawlt를 이렇게 복사해보세요.

```
[cookie_values]
_kawlt=asdf

[chrome]
cookie_file=C:\Users\skang\AppData\Local\Google\Chrome\User Data\Profile 2\Cookies
```

**Comment by jinh0** [comment]
Fixed in #982
